artifact_location: /home/noatnoathacker/.local/lib/python3.8/site-packages/mlflow/filestore_path/0
creation_time: 1698193656186
experiment_id: '0'
last_update_time: 1698193656186
lifecycle_stage: active
name: Default
